Revert making /usr/bin/ read-only
/usr/bin is already on a read-only filesystem, so this was maybe more of
a cosmetic change anyway, but beyond that, something is funky with
Podman now where it won't run.

Errors like this for `podman info`:
newuidmap: write to uid_map failed: Operation not permitted
Error: cannot set up namespace using "/usr/bin/newuidmap": should have
setuid or have filecaps setuid: exit status 1

Seeing if this was the issue, or if it's something else.
We'll find out!